"""
Bagley Configuration Package
Security and general settings
"""

from .security import sanitize_input, check_role, DOCKER_SECURITY_OPTS, RESOURCE_LIMITS, BLOCKED_PATTERNS, ALLOWED_ROLES
from .settings import (
    DISCORD_BOT_TOKEN, COMMAND_PREFIX, DOCKER_NETWORK, CONTAINER_SUBNET,
    MAX_LABS_PER_USER, AUTO_CLEANUP_HOURS, RATE_LIMIT_PER_MINUTE,
    OPENROUTER_API_KEY, AI_MODEL, BASE_DIR, DATA_DIR, LOG_DIR,
    CHALLENGES_DIR, LOG_LEVEL, LOG_FILE, AVAILABLE_LABS,
)

__all__ = [
    "sanitize_input", "check_role", "DOCKER_SECURITY_OPTS", "RESOURCE_LIMITS",
    "BLOCKED_PATTERNS", "ALLOWED_ROLES", "DISCORD_BOT_TOKEN", "COMMAND_PREFIX",
    "DOCKER_NETWORK", "CONTAINER_SUBNET", "MAX_LABS_PER_USER", "AUTO_CLEANUP_HOURS",
    "RATE_LIMIT_PER_MINUTE", "OPENROUTER_API_KEY", "AI_MODEL", "BASE_DIR",
    "DATA_DIR", "LOG_DIR", "CHALLENGES_DIR", "LOG_LEVEL", "LOG_FILE", "AVAILABLE_LABS",
]
